package eu.spitfire_project.smart_service_proxy.backends.parking;

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from http://idi.fundacionctic.org/muo/ucum-instances.owl 
 * @author Auto-generated by schemagen on 27 Apr 2012 10:55 
 */
public class Ucum_instancesVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.oclc.org/NET/muo/ucum";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource UNIT_OF_APOTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-apoth" );
    
    public static final Resource UNIT_OF_AVOIRDUPOIS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-avoirdupois" );
    
    public static final Resource UNIT_OF_BRIT_LENGTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-brit-length" );
    
    public static final Resource UNIT_OF_BRIT_VOLUMES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-brit-volumes" );
    
    public static final Resource UNIT_OF_CGS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-cgs" );
    
    public static final Resource UNIT_OF_CHEMICAL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-chemical" );
    
    public static final Resource UNIT_OF_CLINICAL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-clinical" );
    
    public static final Resource UNIT_OF_CONST = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-const" );
    
    public static final Resource UNIT_OF_DIMLESS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-dimless" );
    
    public static final Resource UNIT_OF_HEAT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-heat" );
    
    public static final Resource UNIT_OF_INFOTECH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-infotech" );
    
    public static final Resource UNIT_OF_INTCUST = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-intcust" );
    
    public static final Resource UNIT_OF_ISO1000 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-iso1000" );
    
    public static final Resource UNIT_OF_LEVELS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-levels" );
    
    public static final Resource UNIT_OF_MISC = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-misc" );
    
    public static final Resource UNIT_OF_SI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-si" );
    
    public static final Resource UNIT_OF_TROY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-troy" );
    
    public static final Resource UNIT_OF_TYPESET = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-typeset" );
    
    public static final Resource UNIT_OF_US_LENGTHS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-us-lengths" );
    
    public static final Resource UNIT_OF_US_VOLUMES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/UnitOf-us-volumes" );
    
    public static final Resource ACCELERATION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/acceleration" );
    
    public static final Resource ACIDITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/acidity" );
    
    public static final Resource ACTION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/action" );
    
    public static final Resource ACTION_AREA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/action-area" );
    
    public static final Resource AMOUNT_OF_INFORMATION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/amount-of-information" );
    
    public static final Resource AMOUNT_OF_SUBSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/amount-of-substance" );
    
    public static final Resource ARBITRARY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/arbitrary" );
    
    public static final Resource ARBITRARY_BIOLOGIC_ACTIVITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/arbitrary-biologic-activity" );
    
    public static final Resource AREA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/area" );
    
    public static final Resource BIOLOGIC_ACTIVITY_ANTISTREPTOLYSIN_O = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-antistreptolysin-O" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_AMYLASE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-amylase" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_ANTICARDIOLIPIN_IG_A = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-anticardiolipin-IgA" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_ANTICARDIOLIPIN_IG_G = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-anticardiolipin-IgG" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_ANTICARDIOLIPIN_IG_M = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-anticardiolipin-IgM" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_FACTOR_VIII_INHIBITOR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-factor-VIII-inhibitor" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_PHOSPHATASE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-phosphatase" );
    
    public static final Resource BIOLOGIC_ACTIVITY_OF_TUBERCULIN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/biologic-activity-of-tuberculin" );
    
    public static final Resource BRIGHTNESS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/brightness" );
    
    public static final Resource CATALYTIC_ACTIVITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/catalytic-activity" );
    
    public static final Resource DEPTH_OF_WATER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/depth-of-water" );
    
    public static final Resource DOSE_EQUIVALENT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/dose-equivalent" );
    
    public static final Resource DRY_VOLUME = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/dry-volume" );
    
    public static final Resource DYNAMIC_VISCOSITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/dynamic-viscosity" );
    
    public static final Resource ELECTRIC_CAPACITANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-capacitance" );
    
    public static final Resource ELECTRIC_CHARGE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-charge" );
    
    public static final Resource ELECTRIC_CONDUCTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-conductance" );
    
    public static final Resource ELECTRIC_CURRENT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-current" );
    
    public static final Resource ELECTRIC_PERMITTIVITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-permittivity" );
    
    public static final Resource ELECTRIC_POTENTIAL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-potential" );
    
    public static final Resource ELECTRIC_POTENTIAL_LEVEL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-potential-level" );
    
    public static final Resource ELECTRIC_RESISTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/electric-resistance" );
    
    public static final Resource ENERGY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/energy" );
    
    public static final Resource ENERGY_DOSE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/energy-dose" );
    
    public static final Resource FLUID_RESISTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/fluid-resistance" );
    
    public static final Resource FLUID_VOLUME = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/fluid-volume" );
    
    public static final Resource FLUX_OF_MAGNETIC_INDUCTION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/flux-of-magnetic-induction" );
    
    public static final Resource FORCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/force" );
    
    public static final Resource FRACTION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/fraction" );
    
    public static final Resource FREQUENCY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/frequency" );
    
    public static final Resource GAUGE_OF_CATHETERS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/gauge-of-catheters" );
    
    public static final Resource HEIGHT_OF_HORSES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/height-of-horses" );
    
    public static final Resource HOMEOPATHIC_POTENCY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/homeopathic-potency" );
    
    public static final Resource ILLUMINANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/illuminance" );
    
    public static final Resource INDUCTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/inductance" );
    
    public static final Resource ION_DOSE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/ion-dose" );
    
    public static final Resource KINEMATIC_VISCOSITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/kinematic-viscosity" );
    
    public static final Resource LENGTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/length" );
    
    public static final Resource LEVEL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/level" );
    
    public static final Resource LINEIC_NUMBER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/lineic-number" );
    
    public static final Resource LUM__INTENSITY_DENSITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/lum.-intensity-density" );
    
    public static final Resource LUMINOUS_FLUX = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/luminous-flux" );
    
    public static final Resource LUMINOUS_INTENSITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/luminous-intensity" );
    
    public static final Resource MAGENTIC_FLUX = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/magentic-flux" );
    
    public static final Resource MAGNETIC_FIELD_INTENSITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/magnetic-field-intensity" );
    
    public static final Resource MAGNETIC_FLUX_DENSITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/magnetic-flux-density" );
    
    public static final Resource MAGNETIC_PERMEABILITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/magnetic-permeability" );
    
    public static final Resource MAGNETIC_TENSION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/magnetic-tension" );
    
    public static final Resource MASS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/mass" );
    
    public static final Resource MASS_FRACTION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/mass-fraction" );
    
    public static final Resource METABOLIC_COST_OF_PHYSICAL_ACTIVITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/metabolic-cost-of-physical-activity" );
    
    public static final Resource NUMBER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/number" );
    
    public static final Resource PLANE_ANGLE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/plane-angle" );
    
    public static final Resource POWER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/power" );
    
    public static final Resource POWER_LEVEL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/power-level" );
    
    public static final Resource PRESSURE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/pressure" );
    
    public static final Resource PRESSURE_LEVEL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/pressure-level" );
    
    public static final Resource RADIOACTIVITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/radioactivity" );
    
    public static final Resource REFRACTION_OF_A_LENS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/refraction-of-a-lens" );
    
    public static final Resource SEDIMENTATION_COEFFICIENT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/sedimentation-coefficient" );
    
    public static final Resource SIGNAL_TRANSMISSION_RATE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/signal-transmission-rate" );
    
    public static final Resource SOLID_ANGLE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/solid-angle" );
    
    public static final Resource TEMPERATURE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/temperature" );
    
    public static final Resource TIME = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/time" );
    
    public static final Resource UNCLASSIFIED = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/unclassified" );
    
    public static final Resource VELOCITY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/velocity" );
    
    public static final Resource VIEW_AREA_IN_MICROSCOPE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/view-area-in-microscope" );
    
    public static final Resource VOLUME = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/volume" );
    
    public static final Resource X_RAY_ATTENUATION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/physical-quality/x-ray-attenuation" );
    
    public static final Resource ATTO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/atto" );
    
    public static final Resource CENTI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/centi" );
    
    public static final Resource DECI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/deci" );
    
    public static final Resource DEKA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/deka" );
    
    public static final Resource EXA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/exa" );
    
    public static final Resource FEMTO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/femto" );
    
    public static final Resource GIBI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/gibi" );
    
    public static final Resource GIGA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/giga" );
    
    public static final Resource HECTO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/hecto" );
    
    public static final Resource KIBI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/kibi" );
    
    public static final Resource KILO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/kilo" );
    
    public static final Resource MEBI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/mebi" );
    
    public static final Resource MEGA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/mega" );
    
    public static final Resource MICRO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/micro" );
    
    public static final Resource MILLI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/milli" );
    
    public static final Resource NANO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/nano" );
    
    public static final Resource PETA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/peta" );
    
    public static final Resource PICO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/pico" );
    
    public static final Resource TEBI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/tebi" );
    
    public static final Resource TERA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/tera" );
    
    public static final Resource YOCTO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/yocto" );
    
    public static final Resource YOTTA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/yotta" );
    
    public static final Resource ZEPTO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/zepto" );
    
    public static final Resource ZETTA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/prefix/zetta" );
    
    public static final Resource GAL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/acceleration/Gal" );
    
    public static final Resource STANDARD_ACCELERATION_OF_FREE_FALL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/acceleration/standard-acceleration-of-free-fall" );
    
    public static final Resource P_H = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/acidity/pH" );
    
    public static final Resource BARN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/action-area/barn" );
    
    public static final Resource PLANCK_CONSTANT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/action/Planck-constant" );
    
    public static final Resource BIT_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-information/bit-1" );
    
    public static final Resource BIT_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-information/bit-2" );
    
    public static final Resource BYTE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-information/byte" );
    
    public static final Resource EQUIVALENTS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-substance/equivalents" );
    
    public static final Resource MOLE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-substance/mole" );
    
    public static final Resource OSMOLE_OF_DISSOLVED_PARTICLES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/amount-of-substance/osmole-of-dissolved-particles" );
    
    public static final Resource KUNKEL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary-biologic-activity/Kunkel-unit" );
    
    public static final Resource MAC_LAGAN_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary-biologic-activity/Mac-Lagan-unit" );
    
    public static final Resource UNITED_STATES_PHARMACOPEIA_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary/United-States-Pharmacopeia-unit" );
    
    public static final Resource ARBITARY_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary/arbitary-unit" );
    
    public static final Resource INTERNATIONAL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/arbitrary/international-unit" );
    
    public static final Resource ACRE_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/acre-1" );
    
    public static final Resource ACRE_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/acre-2" );
    
    public static final Resource ARE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/are" );
    
    public static final Resource CIRCULAR_MIL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/circular-mil" );
    
    public static final Resource SECTION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/section" );
    
    public static final Resource SQUARE_FOOT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/square-foot" );
    
    public static final Resource SQUARE_INCH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/square-inch" );
    
    public static final Resource SQUARE_MILE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/square-mile" );
    
    public static final Resource SQUARE_ROD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/square-rod" );
    
    public static final Resource SQUARE_YARD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/square-yard" );
    
    public static final Resource TOWNSHIP = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/area/township" );
    
    public static final Resource TODD_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-antistreptolysin-O/Todd-unit" );
    
    public static final Resource DYE_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-amylase/Dye-unit" );
    
    public static final Resource SOMOGYI_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-amylase/Somogyi-unit" );
    
    public static final Resource APL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-anticardiolipin-IgA/APL-unit" );
    
    public static final Resource GPL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-anticardiolipin-IgG/GPL-unit" );
    
    public static final Resource MPL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-anticardiolipin-IgM/MPL-unit" );
    
    public static final Resource BETHESDA_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-factor-VIII-inhibitor/Bethesda-unit" );
    
    public static final Resource BODANSKY_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-phosphatase/Bodansky-unit" );
    
    public static final Resource KING_ARMSTRONG_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-phosphatase/King-Armstrong-unit" );
    
    public static final Resource TUBERCULIN_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/biologic-activity-of-tuberculin/tuberculin-unit" );
    
    public static final Resource LAMBERT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/brightness/Lambert" );
    
    public static final Resource UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/catalytic-activity/Unit" );
    
    public static final Resource KATAL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/catalytic-activity/katal" );
    
    public static final Resource FATHOM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/depth-of-water/fathom" );
    
    public static final Resource SIEVERT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dose-equivalent/Sievert" );
    
    public static final Resource RADIATION_EQUIVALENT_MAN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dose-equivalent/radiation-equivalent-man" );
    
    public static final Resource BUSHEL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/bushel" );
    
    public static final Resource DRY_PINT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/dry-pint" );
    
    public static final Resource DRY_QUART = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/dry-quart" );
    
    public static final Resource HISTORICAL_WINCHESTER_GALLON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/historical-winchester-gallon" );
    
    public static final Resource PECK = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dry-volume/peck" );
    
    public static final Resource POISE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/dynamic-viscosity/Poise" );
    
    public static final Resource FARAD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-capacitance/Farad" );
    
    public static final Resource COULOMB = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-charge/Coulomb" );
    
    public static final Resource ELEMENTARY_CHARGE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-charge/elementary-charge" );
    
    public static final Resource SIEMENS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-conductance/Siemens" );
    
    public static final Resource MHO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-conductance/mho" );
    
    public static final Resource AMPERE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-current/Ampere" );
    
    public static final Resource BIOT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-current/Biot" );
    
    public static final Resource PERMITTIVITY_OF_VACUUM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-permittivity/permittivity-of-vacuum" );
    
    public static final Resource BEL_MICROVOLT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential-level/bel-microvolt" );
    
    public static final Resource BEL_MILLIVOLT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential-level/bel-millivolt" );
    
    public static final Resource BEL_VOLT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential-level/bel-volt" );
    
    public static final Resource VOLT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-potential/Volt" );
    
    public static final Resource OHM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/electric-resistance/Ohm" );
    
    public static final Resource GRAY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy-dose/Gray" );
    
    public static final Resource RADIATION_ABSORBED_DOSE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy-dose/radiation-absorbed-dose" );
    
    public static final Resource BRITISH_THERMAL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit" );
    
    public static final Resource BRITISH_THERMAL_UNIT_AT_39_F = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit-at-39_F" );
    
    public static final Resource BRITISH_THERMAL_UNIT_AT_59_F = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit-at-59_F" );
    
    public static final Resource BRITISH_THERMAL_UNIT_AT_60_F = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/British-thermal-unit-at-60_F" );
    
    public static final Resource JOULE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/Joule" );
    
    public static final Resource CALORIE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/calorie" );
    
    public static final Resource CALORIE_AT_15_C = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/calorie-at-15_C" );
    
    public static final Resource CALORIE_AT_20_C = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/calorie-at-20_C" );
    
    public static final Resource ELECTRONVOLT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/electronvolt" );
    
    public static final Resource ERG = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/erg" );
    
    public static final Resource INTERNATIONAL_TABLE_BRITISH_THERMAL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/international-table-British-thermal-unit" );
    
    public static final Resource INTERNATIONAL_TABLE_CALORIE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/international-table-calorie" );
    
    public static final Resource MEAN_BRITISH_THERMAL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/mean-British-thermal-unit" );
    
    public static final Resource MEAN_CALORIE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/mean-calorie" );
    
    public static final Resource NUTRITION_LABEL_CALORIES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/nutrition-label-Calories" );
    
    public static final Resource THERMOCHEMICAL_BRITISH_THERMAL_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/thermochemical-British-thermal-unit" );
    
    public static final Resource THERMOCHEMICAL_CALORIE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/energy/thermochemical-calorie" );
    
    public static final Resource PERIPHERAL_VASCULAR_RESISTANCE_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-resistance/peripheral-vascular-resistance-unit" );
    
    public static final Resource QUEEN_ANNE_S_WINE_GALLON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/Queen_Anne_s-wine-gallon" );
    
    public static final Resource BARREL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/barrel" );
    
    public static final Resource CORD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/cord" );
    
    public static final Resource FLUID_DRAM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/fluid-dram" );
    
    public static final Resource FLUID_OUNCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/fluid-ounce" );
    
    public static final Resource GILL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/gill" );
    
    public static final Resource MINIM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/minim" );
    
    public static final Resource PINT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/pint" );
    
    public static final Resource QUART = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fluid-volume/quart" );
    
    public static final Resource MAXWELL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/flux-of-magnetic-induction/Maxwell" );
    
    public static final Resource NEWTON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/force/Newton" );
    
    public static final Resource DYNE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/force/dyne" );
    
    public static final Resource GRAM_FORCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/force/gram-force" );
    
    public static final Resource POUND_FORCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/force/pound-force" );
    
    public static final Resource PARTS_PER_BILLION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-billion" );
    
    public static final Resource PARTS_PER_MILLION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-million" );
    
    public static final Resource PARTS_PER_THOUSAND = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-thousand" );
    
    public static final Resource PARTS_PER_TRILLION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fraction/parts-per-trillion" );
    
    public static final Resource PERCENT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/fraction/percent" );
    
    public static final Resource HERZ = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/frequency/Herz" );
    
    public static final Resource CHARRIERE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/gauge-of-catheters/Charriere" );
    
    public static final Resource HAND = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/height-of-horses/hand" );
    
    public static final Resource HOMEOPATHIC_POTENCY_OF_CENTESIMAL_SERIES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/homeopathic-potency/homeopathic-potency-of-centesimal-series" );
    
    public static final Resource HOMEOPATHIC_POTENCY_OF_DECIMAL_SERIES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/homeopathic-potency/homeopathic-potency-of-decimal-series" );
    
    public static final Resource LUX = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/illuminance/lux" );
    
    public static final Resource PHOT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/illuminance/phot" );
    
    public static final Resource HENRY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/inductance/Henry" );
    
    public static final Resource ROENTGEN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/ion-dose/Roentgen" );
    
    public static final Resource STOKES = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/kinematic-viscosity/Stokes" );
    
    public static final Resource ANGSTROM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/Angstrom" );
    
    public static final Resource GUNTER_S_CHAIN_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/Gunter_s-chain-1" );
    
    public static final Resource GUNTER_S_CHAIN_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/Gunter_s-chain-2" );
    
    public static final Resource PRINTER_S_PICA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/Printer_s-pica" );
    
    public static final Resource PRINTER_S_POINT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/Printer_s-point" );
    
    public static final Resource RAMDEN_S_CHAIN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/Ramden_s-chain" );
    
    public static final Resource ASTRONOMIC_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/astronomic-unit" );
    
    public static final Resource CICERO = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/cicero" );
    
    public static final Resource DIDOT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/didot" );
    
    public static final Resource FATHOM_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/fathom-1" );
    
    public static final Resource FATHOM_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/fathom-2" );
    
    public static final Resource FOOT_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/foot-1" );
    
    public static final Resource FOOT_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/foot-2" );
    
    public static final Resource FOOT_3 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/foot-3" );
    
    public static final Resource FURLONG = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/furlong" );
    
    public static final Resource INCH_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/inch-1" );
    
    public static final Resource INCH_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/inch-2" );
    
    public static final Resource INCH_3 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/inch-3" );
    
    public static final Resource LIGHT_YEAR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/light-year" );
    
    public static final Resource LIGNE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/ligne" );
    
    public static final Resource LINE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/line" );
    
    public static final Resource LINK_FOR_GUNTER_S_CHAIN_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/link-for-Gunter_s-chain-1" );
    
    public static final Resource LINK_FOR_GUNTER_S_CHAIN_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/link-for-Gunter_s-chain-2" );
    
    public static final Resource LINK_FOR_RAMDEN_S_CHAIN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/link-for-Ramden_s-chain" );
    
    public static final Resource METER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/meter" );
    
    public static final Resource MIL_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/mil-1" );
    
    public static final Resource MIL_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/mil-2" );
    
    public static final Resource MILE_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/mile-1" );
    
    public static final Resource MILE_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/mile-2" );
    
    public static final Resource NAUTIC_MILE_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/nautic-mile-1" );
    
    public static final Resource NAUTIC_MILE_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/nautic-mile-2" );
    
    public static final Resource PACE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/pace" );
    
    public static final Resource PARSEC = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/parsec" );
    
    public static final Resource PICA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/pica" );
    
    public static final Resource PIED = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/pied" );
    
    public static final Resource POINT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/point" );
    
    public static final Resource POUCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/pouce" );
    
    public static final Resource ROD_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/rod-1" );
    
    public static final Resource ROD_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/rod-2" );
    
    public static final Resource STATUTE_MILE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/statute-mile" );
    
    public static final Resource YARD_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/yard-1" );
    
    public static final Resource YARD_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/yard-2" );
    
    public static final Resource YARD_3 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/length/yard-3" );
    
    public static final Resource BEL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/level/bel" );
    
    public static final Resource NEPER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/level/neper" );
    
    public static final Resource KAYSER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/lineic-number/Kayser" );
    
    public static final Resource MESH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/lineic-number/mesh" );
    
    public static final Resource STILB = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/lum.-intensity-density/stilb" );
    
    public static final Resource LUMEN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/luminous-flux/lumen" );
    
    public static final Resource CANDELA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/luminous-intensity/candela" );
    
    public static final Resource WEBER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/magentic-flux/Weber" );
    
    public static final Resource OERSTED = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-field-intensity/Oersted" );
    
    public static final Resource GAUSS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-flux-density/Gauss" );
    
    public static final Resource TESLA = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-flux-density/Tesla" );
    
    public static final Resource PERMEABILITY_OF_VACUUM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-permeability/permeability-of-vacuum" );
    
    public static final Resource GILBERT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/magnetic-tension/Gilbert" );
    
    public static final Resource CARAT_OF_GOLD_ALLOYS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass-fraction/carat-of-gold-alloys" );
    
    public static final Resource GRAM_PERCENT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass-fraction/gram-percent" );
    
    public static final Resource DRAM_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/dram-1" );
    
    public static final Resource DRAM_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/dram-2" );
    
    public static final Resource ELECTRON_MASS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/electron-mass" );
    
    public static final Resource GRAIN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/grain" );
    
    public static final Resource GRAM = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/gram" );
    
    public static final Resource LONG_HUNDERDWEIGHT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/long-hunderdweight" );
    
    public static final Resource LONG_TON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/long-ton" );
    
    public static final Resource METRIC_CARAT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/metric-carat" );
    
    public static final Resource OUNCE_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/ounce-1" );
    
    public static final Resource OUNCE_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/ounce-2" );
    
    public static final Resource OUNCE_3 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/ounce-3" );
    
    public static final Resource PENNYWEIGHT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/pennyweight" );
    
    public static final Resource POUND_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/pound-1" );
    
    public static final Resource POUND_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/pound-2" );
    
    public static final Resource POUND_3 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/pound-3" );
    
    public static final Resource PROTON_MASS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/proton-mass" );
    
    public static final Resource SCRUPLE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/scruple" );
    
    public static final Resource SHORT_HUNDREDWEIGHT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/short-hundredweight" );
    
    public static final Resource SHORT_TON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/short-ton" );
    
    public static final Resource STONE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/stone" );
    
    public static final Resource TONNE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/tonne" );
    
    public static final Resource UNIFIED_ATOMIC_MASS_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/mass/unified-atomic-mass-unit" );
    
    public static final Resource METABOLIC_EQUIVALENT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/metabolic-cost-of-physical-activity/metabolic-equivalent" );
    
    public static final Resource THE_NUMBER_PI = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/number/the-number-pi" );
    
    public static final Resource THE_NUMBER_TEN_FOR_ARBITRARY_POWERS_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/number/the-number-ten-for-arbitrary-powers-1" );
    
    public static final Resource THE_NUMBER_TEN_FOR_ARBITRARY_POWERS_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/number/the-number-ten-for-arbitrary-powers-2" );
    
    public static final Resource CIRCLE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/circle" );
    
    public static final Resource DEGREE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/degree" );
    
    public static final Resource GON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/gon" );
    
    public static final Resource MINUTE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/minute" );
    
    public static final Resource RADIAN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/radian" );
    
    public static final Resource SECOND = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/plane-angle/second" );
    
    public static final Resource BEL_KILOWATT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/power-level/bel-kilowatt" );
    
    public static final Resource BEL_WATT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/power-level/bel-watt" );
    
    public static final Resource WATT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/power/Watt" );
    
    public static final Resource HORSEPOWER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/power/horsepower" );
    
    public static final Resource BEL_SOUND_PRESSURE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure-level/bel-sound-pressure" );
    
    public static final Resource PASCAL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/Pascal" );
    
    public static final Resource BAR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/bar" );
    
    public static final Resource INCH_OF_MERCURY_COLUMN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/inch-of-mercury-column" );
    
    public static final Resource INCH_OF_WATER_COLUMN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/inch-of-water-column" );
    
    public static final Resource METER_OF_MERCURY_COLUMN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/meter-of-mercury-column" );
    
    public static final Resource METER_OF_WATER_COLUMN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/meter-of-water-column" );
    
    public static final Resource POUND_PER_SQARE_INCH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/pound-per-sqare-inch" );
    
    public static final Resource STANDARD_ATMOSPHERE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/standard-atmosphere" );
    
    public static final Resource TECHNICAL_ATMOSPHERE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/pressure/technical-atmosphere" );
    
    public static final Resource BECQUEREL = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/radioactivity/Becquerel" );
    
    public static final Resource CURIE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/radioactivity/Curie" );
    
    public static final Resource DIOPTER = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/refraction-of-a-lens/diopter" );
    
    public static final Resource SVEDBERG_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/sedimentation-coefficient/Svedberg-unit" );
    
    public static final Resource BAUD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/signal-transmission-rate/baud" );
    
    public static final Resource SPERE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/solid-angle/spere" );
    
    public static final Resource STREADIAN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/solid-angle/streadian" );
    
    public static final Resource KELVIN = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/temperature/Kelvin" );
    
    public static final Resource DEGREE_CELSIUS = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/temperature/degree-Celsius" );
    
    public static final Resource DEGREE_FAHRENHEIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/temperature/degree-Fahrenheit" );
    
    public static final Resource DAY = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/day" );
    
    public static final Resource HOUR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/hour" );
    
    public static final Resource MEAN_GREGORIAN_MONTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Gregorian-month" );
    
    public static final Resource MEAN_GREGORIAN_YEAR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Gregorian-year" );
    
    public static final Resource MEAN_JULIAN_MONTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Julian-month" );
    
    public static final Resource MEAN_JULIAN_YEAR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/mean-Julian-year" );
    
    public static final Resource MINUTE_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/minute" );
    
    public static final Resource MONTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/month" );
    
    public static final Resource SECOND_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/second" );
    
    public static final Resource SYNODAL_MONTH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/synodal-month" );
    
    public static final Resource TROPICAL_YEAR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/tropical-year" );
    
    public static final Resource WEEK = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/week" );
    
    public static final Resource YEAR = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/time/year" );
    
    public static final Resource BOLTZMANN_CONSTANT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/unclassified/Boltzmann-constant" );
    
    public static final Resource NEWTONIAN_CONSTANT_OF_GRAVITATION = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/unclassified/Newtonian-constant-of-gravitation" );
    
    public static final Resource KNOT_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/velocity/knot-1" );
    
    public static final Resource KNOT_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/velocity/knot-2" );
    
    public static final Resource VELOCITY_OF_LIGHT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/velocity/velocity-of-light" );
    
    public static final Resource HIGH_POWER_FIELD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/view-area-in-microscope/high-power-field" );
    
    public static final Resource LOW_POWER_FIELD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/view-area-in-microscope/low-power-field" );
    
    public static final Resource BOARD_FOOT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/board-foot" );
    
    public static final Resource BUSHEL_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/bushel" );
    
    public static final Resource CORD_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/cord" );
    
    public static final Resource CUBIC_FOOT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/cubic-foot" );
    
    public static final Resource CUBIC_INCH = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/cubic-inch" );
    
    public static final Resource CUBIC_YARD = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/cubic-yard" );
    
    public static final Resource CUP = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/cup" );
    
    public static final Resource DROP = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/drop" );
    
    public static final Resource FLUID_DRAM_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/fluid-dram" );
    
    public static final Resource FLUID_OUNCE_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/fluid-ounce" );
    
    public static final Resource GALLON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/gallon" );
    
    public static final Resource GILL_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/gill" );
    
    public static final Resource LITER_1 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/liter-1" );
    
    public static final Resource LITER_2 = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/liter-2" );
    
    public static final Resource MINIM_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/minim" );
    
    public static final Resource PECK_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/peck" );
    
    public static final Resource PINT_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/pint" );
    
    public static final Resource QUART_INSTANCE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/quart" );
    
    public static final Resource STERE = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/stere" );
    
    public static final Resource TABLESPOON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/tablespoon" );
    
    public static final Resource TEASPOON = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/volume/teaspoon" );
    
    public static final Resource HOUNSFIELD_UNIT = m_model.createResource( "http://purl.oclc.org/NET/muo/ucum/unit/x-ray-attenuation/Hounsfield-unit" );
    
}
